### ISSUE TITLE
'rcn=4' vs 'rcn=4&fu=1' differences

### ISSUE THREAD

**Issue by Spongman** [ankraft/ACME-oneM2M-CSE#60]
i believe there is an issue rendering attributes+child_resources responses, nesting of the resources in the response is different between retrieve and discovery, and i don't believe this is justified in the spec.

for example, 

`http://127.0.0.1:8081/id-in?rc=4` returns

```
{
    "m2m:cb": {
        "ri": "id-in",
        "ty": 5,
        "rn": "cse-in",
        "csi": "/id-in",
        "acpi": [
            "acpAdmin"
        ],
        "ct": "20200609T200331,388077",
        "lt": "20200609T202105,236548",
        "et": "20210609T200331,388176",
        "pi": "",
        "rr": false,
        "srt": [
            1,
            2,
            3,
            4,
            5,
            9,
            13,
            14,
            16,
            23,
            28,
            52
        ],
        "csz": [
            "application/json"
        ],
        "srv": [
            "3"
        ],
        "poa": [
            "http://127.0.0.1:8080"
        ],
        "cst": 1,
        "nl": "nod861042590844046387",
        "m2m:acp": [
            {
                "ri": "acp1028273287565921797",
                "rn": "acp_statistics",
                "ct": "20200609T200338,574776",
                "lt": "20200609T200338,574776",
                "et": "20210609T200338,574845",
                "pi": "id-in",
                "ty": 1,
                "pv": {
                    "acr": [
                        {
                            "acop": 63,
                            "acor": [
                                "CAdmin",
                                "CX677vJit2W"
                            ]
                        }
                    ]
                },
                "pvs": {
                    "acr": [
                        {
                            "acop": 51,
                            "acor": [
                                "CAdmin"
                            ]
                        }
                    ]
                }
            },
            {
                "ty": 1,
                "ri": "acpAdmin",
                "rn": "adminACP",
                "pi": "id-in",
                "pv": {
                    "acr": [
                        {
                            "acor": [
                                "CAdmin"
                            ],
                            "acop": 63
                        }
                    ]
                },
                "pvs": {
                    "acr": [
                        {
                            "acor": [
                                "CAdmin"
                            ],
                            "acop": 55
                        }
                    ]
                },
                "ct": "20200609T200331,455044",
                "lt": "20200609T200331,455044",
                "et": "20210609T200331,455162"
            },
            {
                "ty": 1,
                "ri": "acpDefault",
                "rn": "defaultACP",
                "pi": "id-in",
                "pv": {
                    "acr": [
                        {
                            "acor": [
                                "CDefault",
                                "CAdmin"
                            ],
                            "acop": 63
                        }
                    ]
                },
                "pvs": {
                    "acr": [
                        {
                            "acor": [
                                "CAdmin"
                            ],
                            "acop": 55
                        }
                    ]
                },
                "ct": "20200609T200331,513529",
                "lt": "20200609T200331,513529",
                "et": "20210609T200331,513600"
            }
        ],
        "m2m:ae": [
            {
                "rn": "statistics",
                "api": "ae-statistics",
                "nl": "nod861042590844046387",
                "poa": [
                    "http://127.0.0.1:8080"
                ],
                "rr": true,
                "srv": [
                    "3",
                    "4"
                ],
                "ri": "CX677vJit2W",
                "ct": "20200609T200338,558810",
                "lt": "20200609T200338,558810",
                "et": "20210609T200338,558877",
                "pi": "id-in",
                "ty": 2,
                "aei": "CX677vJit2W",
                "acpi": [
                    "acp1028273287565921797"
                ],
                "acme:csest": [
                    {
                        "rn": "statistics",
                        "cnd": "acme.statistics",
                        "acpi": [
                            "acp1028273287565921797"
                        ],
                        "mni": 10,
                        "rmRes": 4984,
                        "crRes": 5003,
                        "htRet": 2251,
                        "htCre": 6,
                        "htUpd": 5114,
                        "htDel": 0,
                        "lgErr": 4,
                        "lgWrn": 9540,
                        "cseSU": "20200708T005406,868457",
                        "cseUT": "0:31:12",
                        "ctRes": 19,
                        "ri": "csest2319516495356652035",
                        "ct": "20200609T200338,971435",
                        "lt": "20200707T182519,810517",
                        "et": "20210609T200338,971524",
                        "pi": "CX677vJit2W",
                        "st": 5006,
                        "ty": 28,
                        "cs": 375,
                        "cr": "CX677vJit2W",
                        "cni": 10,
                        "acme:csest": [
                            {
                                "rn": "statistics_4997",
                                "rmRes": 4975,
                                "crRes": 4994,
                                "htRet": 2212,
                                "htCre": 6,
                                "htUpd": 5099,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:29:41",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest1794142844999499776",
                                "ct": "20200707T182348,711692",
                                "lt": "20200707T182348,711692",
                                "et": "20210707T182348,711708",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_4998",
                                "rmRes": 4976,
                                "crRes": 4995,
                                "htRet": 2213,
                                "htCre": 6,
                                "htUpd": 5100,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:29:51",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest3357060219620329572",
                                "ct": "20200707T182358,823487",
                                "lt": "20200707T182358,823487",
                                "et": "20210707T182358,823501",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_4999",
                                "rmRes": 4977,
                                "crRes": 4996,
                                "htRet": 2213,
                                "htCre": 6,
                                "htUpd": 5101,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:02",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest4226788739776195818",
                                "ct": "20200707T182408,912666",
                                "lt": "20200707T182408,912666",
                                "et": "20210707T182408,912689",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5000",
                                "rmRes": 4978,
                                "crRes": 4997,
                                "htRet": 2213,
                                "htCre": 6,
                                "htUpd": 5105,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:12",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest2267622056735906608",
                                "ct": "20200707T182419,035917",
                                "lt": "20200707T182419,035917",
                                "et": "20210707T182419,035934",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5001",
                                "rmRes": 4979,
                                "crRes": 4998,
                                "htRet": 2231,
                                "htCre": 6,
                                "htUpd": 5106,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:22",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest7183147931901019038",
                                "ct": "20200707T182429,156655",
                                "lt": "20200707T182429,156655",
                                "et": "20210707T182429,156672",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5002",
                                "rmRes": 4980,
                                "crRes": 4999,
                                "htRet": 2249,
                                "htCre": 6,
                                "htUpd": 5107,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:32",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest7061487257687262039",
                                "ct": "20200707T182439,240053",
                                "lt": "20200707T182439,240053",
                                "et": "20210707T182439,240067",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5003",
                                "rmRes": 4981,
                                "crRes": 5000,
                                "htRet": 2249,
                                "htCre": 6,
                                "htUpd": 5108,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:42",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest8803525397679550584",
                                "ct": "20200707T182449,360863",
                                "lt": "20200707T182449,360863",
                                "et": "20210707T182449,360893",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5004",
                                "rmRes": 4982,
                                "crRes": 5001,
                                "htRet": 2249,
                                "htCre": 6,
                                "htUpd": 5109,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:52",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest4214835427562517289",
                                "ct": "20200707T182459,466163",
                                "lt": "20200707T182459,466163",
                                "et": "20210707T182459,466188",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5005",
                                "rmRes": 4983,
                                "crRes": 5002,
                                "htRet": 2249,
                                "htCre": 6,
                                "htUpd": 5110,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:31:02",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest2570218605739078081",
                                "ct": "20200707T182509,546456",
                                "lt": "20200707T182509,546456",
                                "et": "20210707T182509,546470",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5006",
                                "rmRes": 4984,
                                "crRes": 5003,
                                "htRet": 2251,
                                "htCre": 6,
                                "htUpd": 5114,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:31:12",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest5796550581764529614",
                                "ct": "20200707T182519,813047",
                                "lt": "20200707T182519,813047",
                                "et": "20210707T182519,813074",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            }
                        ]
                    }
                ]
            }
        ],
        "m2m:nod": [
            {
                "rn": "cse-node",
                "ni": "cse-node",
                "ri": "nod861042590844046387",
                "ct": "20200609T200336,857603",
                "lt": "20200609T200338,706035",
                "et": "20210609T200336,857686",
                "pi": "id-in",
                "ty": 14,
                "acpi": [
                    "acpDefault"
                ],
                "hcl": "id-in",
                "hael": [
                    "CX677vJit2W"
                ],
                "m2m:bat": [
                    {
                        "mgd": 1006,
                        "dc": "battery",
                        "rn": "battery",
                        "btl": 0,
                        "bts": 6,
                        "ri": "bat2485569212438296813",
                        "ct": "20200609T200337,533813",
                        "lt": "20200707T182518,985643",
                        "et": "20210609T200337,533879",
                        "pi": "nod861042590844046387",
                        "ty": 13,
                        "acpi": [
                            "acpDefault"
                        ]
                    },
                    {
                        "mgd": 1007,
                        "dc": "deviceInfo",
                        "rn": "deviceinfo",
                        "dlb": "| IP:127.0.1.1 MAC:70:85:c2:d2:51:14",
                        "dvnm": "machine",
                        "osv": "Linux 4.4.0-19041-Microsoft x86_64",
                        "syst": "20200707T182519,021760",
                        "ri": "dvi8024400728351037531",
                        "ct": "20200609T200338,113010",
                        "lt": "20200707T182519,033519",
                        "et": "20210609T200338,113079",
                        "pi": "nod861042590844046387",
                        "ty": 13,
                        "dty": "unknown",
                        "mod": "unknown",
                        "man": "unknown",
                        "acpi": [
                            "acpDefault"
                        ]
                    },
                    {
                        "mgd": 1003,
                        "dc": "memory",
                        "rn": "memory",
                        "mma": 3261923328,
                        "mmt": 16819085312,
                        "ri": "mem9051650140950871829",
                        "ct": "20200609T200337,821163",
                        "lt": "20200707T182519,015745",
                        "et": "20210609T200337,821244",
                        "pi": "nod861042590844046387",
                        "ty": 13,
                        "acpi": [
                            "acpDefault"
                        ]
                    }
                ]
            }
        ]
    }
}
```

whereas `http://127.0.0.1:8081/id-in?rc=4` returns

```
{
    "m2m:cb": {
        "ri": "id-in",
        "ty": 5,
        "rn": "cse-in",
        "csi": "/id-in",
        "acpi": [
            "acpAdmin"
        ],
        "ct": "20200609T200331,388077",
        "lt": "20200609T202105,236548",
        "et": "20210609T200331,388176",
        "pi": "",
        "rr": false,
        "srt": [
            1,
            2,
            3,
            4,
            5,
            9,
            13,
            14,
            16,
            23,
            28,
            52
        ],
        "csz": [
            "application/json"
        ],
        "srv": [
            "3"
        ],
        "poa": [
            "http://127.0.0.1:8080"
        ],
        "cst": 1,
        "nl": "nod861042590844046387",
        "m2m:acp": [
            {
                "ri": "acp1028273287565921797",
                "rn": "acp_statistics",
                "ct": "20200609T200338,574776",
                "lt": "20200609T200338,574776",
                "et": "20210609T200338,574845",
                "pi": "id-in",
                "ty": 1,
                "pv": {
                    "acr": [
                        {
                            "acop": 63,
                            "acor": [
                                "CAdmin",
                                "CX677vJit2W"
                            ]
                        }
                    ]
                },
                "pvs": {
                    "acr": [
                        {
                            "acop": 51,
                            "acor": [
                                "CAdmin"
                            ]
                        }
                    ]
                }
            },
            {
                "ty": 1,
                "ri": "acpAdmin",
                "rn": "adminACP",
                "pi": "id-in",
                "pv": {
                    "acr": [
                        {
                            "acor": [
                                "CAdmin"
                            ],
                            "acop": 63
                        }
                    ]
                },
                "pvs": {
                    "acr": [
                        {
                            "acor": [
                                "CAdmin"
                            ],
                            "acop": 55
                        }
                    ]
                },
                "ct": "20200609T200331,455044",
                "lt": "20200609T200331,455044",
                "et": "20210609T200331,455162"
            },
            {
                "ty": 1,
                "ri": "acpDefault",
                "rn": "defaultACP",
                "pi": "id-in",
                "pv": {
                    "acr": [
                        {
                            "acor": [
                                "CDefault",
                                "CAdmin"
                            ],
                            "acop": 63
                        }
                    ]
                },
                "pvs": {
                    "acr": [
                        {
                            "acor": [
                                "CAdmin"
                            ],
                            "acop": 55
                        }
                    ]
                },
                "ct": "20200609T200331,513529",
                "lt": "20200609T200331,513529",
                "et": "20210609T200331,513600"
            }
        ],
        "m2m:ae": [
            {
                "rn": "statistics",
                "api": "ae-statistics",
                "nl": "nod861042590844046387",
                "poa": [
                    "http://127.0.0.1:8080"
                ],
                "rr": true,
                "srv": [
                    "3",
                    "4"
                ],
                "ri": "CX677vJit2W",
                "ct": "20200609T200338,558810",
                "lt": "20200609T200338,558810",
                "et": "20210609T200338,558877",
                "pi": "id-in",
                "ty": 2,
                "aei": "CX677vJit2W",
                "acpi": [
                    "acp1028273287565921797"
                ],
                "acme:csest": [
                    {
                        "rn": "statistics",
                        "cnd": "acme.statistics",
                        "acpi": [
                            "acp1028273287565921797"
                        ],
                        "mni": 10,
                        "rmRes": 4984,
                        "crRes": 5003,
                        "htRet": 2251,
                        "htCre": 6,
                        "htUpd": 5114,
                        "htDel": 0,
                        "lgErr": 4,
                        "lgWrn": 9540,
                        "cseSU": "20200708T005406,868457",
                        "cseUT": "0:31:12",
                        "ctRes": 19,
                        "ri": "csest2319516495356652035",
                        "ct": "20200609T200338,971435",
                        "lt": "20200707T182519,810517",
                        "et": "20210609T200338,971524",
                        "pi": "CX677vJit2W",
                        "st": 5006,
                        "ty": 28,
                        "cs": 375,
                        "cr": "CX677vJit2W",
                        "cni": 10,
                        "acme:csest": [
                            {
                                "rn": "statistics_4997",
                                "rmRes": 4975,
                                "crRes": 4994,
                                "htRet": 2212,
                                "htCre": 6,
                                "htUpd": 5099,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:29:41",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest1794142844999499776",
                                "ct": "20200707T182348,711692",
                                "lt": "20200707T182348,711692",
                                "et": "20210707T182348,711708",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_4998",
                                "rmRes": 4976,
                                "crRes": 4995,
                                "htRet": 2213,
                                "htCre": 6,
                                "htUpd": 5100,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:29:51",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest3357060219620329572",
                                "ct": "20200707T182358,823487",
                                "lt": "20200707T182358,823487",
                                "et": "20210707T182358,823501",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_4999",
                                "rmRes": 4977,
                                "crRes": 4996,
                                "htRet": 2213,
                                "htCre": 6,
                                "htUpd": 5101,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:02",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest4226788739776195818",
                                "ct": "20200707T182408,912666",
                                "lt": "20200707T182408,912666",
                                "et": "20210707T182408,912689",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5000",
                                "rmRes": 4978,
                                "crRes": 4997,
                                "htRet": 2213,
                                "htCre": 6,
                                "htUpd": 5105,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:12",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest2267622056735906608",
                                "ct": "20200707T182419,035917",
                                "lt": "20200707T182419,035917",
                                "et": "20210707T182419,035934",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5001",
                                "rmRes": 4979,
                                "crRes": 4998,
                                "htRet": 2231,
                                "htCre": 6,
                                "htUpd": 5106,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:22",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest7183147931901019038",
                                "ct": "20200707T182429,156655",
                                "lt": "20200707T182429,156655",
                                "et": "20210707T182429,156672",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5002",
                                "rmRes": 4980,
                                "crRes": 4999,
                                "htRet": 2249,
                                "htCre": 6,
                                "htUpd": 5107,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:32",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest7061487257687262039",
                                "ct": "20200707T182439,240053",
                                "lt": "20200707T182439,240053",
                                "et": "20210707T182439,240067",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5003",
                                "rmRes": 4981,
                                "crRes": 5000,
                                "htRet": 2249,
                                "htCre": 6,
                                "htUpd": 5108,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:42",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest8803525397679550584",
                                "ct": "20200707T182449,360863",
                                "lt": "20200707T182449,360863",
                                "et": "20210707T182449,360893",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5004",
                                "rmRes": 4982,
                                "crRes": 5001,
                                "htRet": 2249,
                                "htCre": 6,
                                "htUpd": 5109,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:30:52",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest4214835427562517289",
                                "ct": "20200707T182459,466163",
                                "lt": "20200707T182459,466163",
                                "et": "20210707T182459,466188",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5005",
                                "rmRes": 4983,
                                "crRes": 5002,
                                "htRet": 2249,
                                "htCre": 6,
                                "htUpd": 5110,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:31:02",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest2570218605739078081",
                                "ct": "20200707T182509,546456",
                                "lt": "20200707T182509,546456",
                                "et": "20210707T182509,546470",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            },
                            {
                                "rn": "statistics_5006",
                                "rmRes": 4984,
                                "crRes": 5003,
                                "htRet": 2251,
                                "htCre": 6,
                                "htUpd": 5114,
                                "htDel": 0,
                                "lgErr": 4,
                                "lgWrn": 9540,
                                "cseSU": "20200708T005406,868457",
                                "cseUT": "0:31:12",
                                "ctRes": 19,
                                "acpi": [
                                    "acp1028273287565921797"
                                ],
                                "ri": "csest5796550581764529614",
                                "ct": "20200707T182519,813047",
                                "lt": "20200707T182519,813047",
                                "et": "20210707T182519,813074",
                                "pi": "csest2319516495356652035",
                                "st": 0,
                                "ty": 52,
                                "cs": 375
                            }
                        ]
                    }
                ]
            }
        ],
        "m2m:bat": [
            {
                "mgd": 1006,
                "dc": "battery",
                "rn": "battery",
                "btl": 0,
                "bts": 6,
                "ri": "bat2485569212438296813",
                "ct": "20200609T200337,533813",
                "lt": "20200707T182518,985643",
                "et": "20210609T200337,533879",
                "pi": "nod861042590844046387",
                "ty": 13,
                "acpi": [
                    "acpDefault"
                ]
            },
            {
                "mgd": 1007,
                "dc": "deviceInfo",
                "rn": "deviceinfo",
                "dlb": "| IP:127.0.1.1 MAC:70:85:c2:d2:51:14",
                "dvnm": "machine",
                "osv": "Linux 4.4.0-19041-Microsoft x86_64",
                "syst": "20200707T182519,021760",
                "ri": "dvi8024400728351037531",
                "ct": "20200609T200338,113010",
                "lt": "20200707T182519,033519",
                "et": "20210609T200338,113079",
                "pi": "nod861042590844046387",
                "ty": 13,
                "dty": "unknown",
                "mod": "unknown",
                "man": "unknown",
                "acpi": [
                    "acpDefault"
                ]
            },
            {
                "mgd": 1003,
                "dc": "memory",
                "rn": "memory",
                "mma": 3261923328,
                "mmt": 16819085312,
                "ri": "mem9051650140950871829",
                "ct": "20200609T200337,821163",
                "lt": "20200707T182519,015745",
                "et": "20210609T200337,821244",
                "pi": "nod861042590844046387",
                "ty": 13,
                "acpi": [
                    "acpDefault"
                ]
            }
        ],
        "m2m:nod": [
            {
                "rn": "cse-node",
                "ni": "cse-node",
                "ri": "nod861042590844046387",
                "ct": "20200609T200336,857603",
                "lt": "20200609T200338,706035",
                "et": "20210609T200336,857686",
                "pi": "id-in",
                "ty": 14,
                "acpi": [
                    "acpDefault"
                ],
                "hcl": "id-in",
                "hael": [
                    "CX677vJit2W"
                ]
            }
        ]
    }
}
```

diff these and you'll see that in the `fu=1` response the tree is flattened. i believe this is a bug.

**Comment by ankraft** [comment]
Thanks for reporting this. This should be fixed now.
Sorting the result set at the wrong time messed up the internal structure.

**Comment by Spongman** [comment]
yes, i'm using the development branch. Can you please double check the sheet at https://docs.google.com/spreadsheets/d/1_eQOpghaDnWzYZ672pvBS77yFupSVEuNORSO_qin2mY that shows the different responses for different combinations of the `rcn`, `fu` and `drt` parameters. i'm still not convinced they all match up with what's in the spec, but i find the spec so vague on this still that it's difficult for me to come up with reasons.

**Comment by reinaortega** [comment]
Hi, 
In fact, rcn=4 should not be used for Discovery operation. That's only valid for Retrieve (normal retrieve) and Delete operation as specified in TS-0001. When valid for Discovery operation it is mentioned explicitly. 
Both TS-0001 and TS-0004 will be updated to clarify that.

**Comment by Spongman** [comment]
> In fact, rcn=4 should not be used for Discovery operation.


reallly? that directly contradicts what Andreas told me before. and this would seem to be confirmed by this issue & fix: https://github.com/ankraft/ACME-oneM2M-CSE/issues/41

**Comment by ankraft** [comment]
I fact It seems that I was wrong about this. We talked about this issue today and it seems that the respective clause in TS-0004 does in fact not correctly describe what is (only vaguely) specified in TS-0001. I am sorry.

**Comment by Spongman** [comment]
can you please explain the differences between the results for `rcn=8` and `rcn=8&fu=1`:

`rcn=8`:

````
{
    "m2m:cb": {
        "m2m:acp": []
        ...
````


`rcn=8&fu=1`:

````
{
    "m2m:acp": []
    ...
````

i'm really having a hard time working out where in the spec it says that the responses should look like this. Regardless, I cannot see why these results should be different.

**Comment by Spongman** [comment]
> When valid for Discovery operation it is mentioned explicitly.

Can you please point me to the place in the spec where the valid Discovery results types are "mentioned explicitly" ?

**Comment by reinaortega** [comment]
Hi, 

Same case as for rcn=4, that is not valid for Discovery operation. You can find that in TS-0001 8.1.2 where there's only one rcn value (child-resources-references) for which Discovery mechanism can be used. And also TS-0004 7.5.2-2, where only URIList and resourceRefList are possible response content for Discovery operation. Both TS-0001 and TS-0004 will be updated to clarify that. As info, only rcn=6 (child-resources-references) and rcn not present are valid for Discovery operation.

**Comment by Spongman** [comment]
Fantastic, thanks for clearing that up.

**Comment by Spongman** [comment]
so, where in the spec does it say what the format of these responses is supposed to be?

for example, i'm looking at the `rcn=8` response, which looks like this:

```
{
    "cb": {
        "acp": [
            {
               ...
```


however, this doesn't look right to me, because returning an empty parent resource ( `ch` in this example) like that would seem to contravene some of the minOccurs requirements in the xsd for some resources. any compliant deserializer is going to reject that as an invalid resource.

i would have expected the response to just contains the child resources, eg:

```
{
    "acp": [
        {
           ...
```

... but i cannot find anything in the spec that states which is correct.

**Comment by reinaortega** [comment]
All protocol related stuff is in TS-0004, including format of responses. In TS-0004 table 7.5.2-2, you find which element the content response should contain according to the operation/rcn value. In your case, R/8 of the CSEBase will return the CSEBase with only child resources (just as you indicated).
Regarding your question about XSD, in TS-0004 clause 7.2.1.1, you can find that for partial resources (which is the case) , _"since a partial resource is being transferred it is not required to be valid according to the XSD for that resource in terms of the presence of resource attributes"_
